/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyPanel', {
    extend: 'Ext.Panel',

    config: {
        style: 'background-color: #1e1e1e',
        layout: {
            type: 'vbox'
        },
        items: [
            {
                xtype: 'tabpanel',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'container',
                        title: 'Home'
                    },
                    {
                        xtype: 'container',
                        title: 'Tab 2'
                    },
                    {
                        xtype: 'container',
                        title: 'Tab 3'
                    }
                ]
            },
            {
                xtype: 'panel',
                items: [
                    {
                        xtype: 'titlebar',
                        docked: 'top',
                        title: 'Starbucks'
                    }
                ]
            },
            {
                xtype: 'container',
                height: 64,
                margin: '10 50 0 50',
                width: 212,
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        height: 64,
                        margin: '0 10 0 0',
                        padding: '',
                        style: 'border-radius: 0px; border: 1px solid transparent; background-image: url(images/icons/main/my_drinks.png); background-size: contain; background-repeat: no-repeat;',
                        width: 64,
                        icon: '',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        height: 64,
                        padding: '',
                        style: 'border-radius: 0px; border: 1px solid transparent; background-image: url(images/icons/main/favorites.png); background-size: contain; background-repeat: no-repeat;',
                        width: 64,
                        icon: '',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        height: 64,
                        margin: '0 0 0 10',
                        padding: '',
                        style: 'border-radius: 0px; border: 1px solid transparent; background-image: url(images/icons/main/coffees.png); background-size: contain; background-repeat: no-repeat;',
                        width: 64,
                        icon: '',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                height: 64,
                margin: '10 50 0 50',
                width: 212,
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        height: 64,
                        margin: '0 10 0 0',
                        padding: '',
                        style: 'border-radius: 0px; border: 1px solid transparent; background-image: url(images/icons/main/food.png); background-size: contain; background-repeat: no-repeat;',
                        width: 64,
                        icon: '',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        height: 64,
                        padding: '',
                        style: 'border-radius: 0px; border: 1px solid transparent; background-image: url(images/icons/main/drinks.png); background-size: contain; background-repeat: no-repeat;',
                        width: 64,
                        icon: '',
                        text: ''
                    },
                    {
                        xtype: 'button',
                        flex: 1,
                        height: 64,
                        margin: '0 0 0 10',
                        padding: '',
                        style: 'border-radius: 0px; border: 1px solid transparent; background-image: url(images/icons/main/settings.png); background-size: contain; background-repeat: no-repeat;',
                        width: 64,
                        icon: '',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'container',
                height: 64,
                margin: '10 50 0 50',
                width: 64,
                layout: {
                    type: 'hbox'
                },
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        height: 64,
                        padding: '',
                        style: 'border-radius: 0px; border: 1px solid transparent; background-image: url(images/icons/main/help.png); background-size: contain; background-repeat: no-repeat;',
                        width: '64px',
                        icon: '',
                        text: ''
                    }
                ]
            }
        ]
    }

});